# This is a sample file, for detailed reference see: https://www.rudderstack.com/docs/profiles/get-started/profile-builder
models:
  - name: user_id_stitcher
    model_type: id_stitcher
    model_spec:
      entity_key: user
      edge_sources:
        - from: inputs/rsIdentifies
        - from: inputs/rsTracks

var_groups:
  - name: default_vars
    entity_key: user
    vars:
      - entity_var:
          name: first_seen
          select: min(cast(timestamp as date))
          from: inputs/rsTracks
          is_feature: false
      - entity_var:
          name: last_seen
          select: max(cast(timestamp as date))
          from: inputs/rsTracks
          is_feature: false
      - entity_var:
          name: user_lifespan
          select: '{{user.last_seen}} - {{user.first_seen}}'
          description: Life Time Value of a customer
      - entity_var:
          name: days_active
          select: count(distinct cast(timestamp as date))
          from: inputs/rsTracks
          description: No. of days a customer was active
